# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: redeHoteleira.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'redeHoteleira.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13redeHoteleira.proto\x12\rredeHoteleira\"L\n\x10\x42ookHotelRequest\x12\x12\n\nhotel_name\x18\x01 \x01(\t\x12\x10\n\x08qtd_days\x18\x02 \x01(\x05\x12\x12\n\nqtd_guests\x18\x03 \x01(\x05\"L\n\x11\x42ookHotelResponse\x12\x0e\n\x06sucess\x18\x01 \x01(\x08\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x03 \x01(\tB\x05\n\x03_id\"$\n\x16\x43\x61ncelBookHotelRequest\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x17\x43\x61ncelBookHotelResponse\x12\x0e\n\x06sucess\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc1\x01\n\rRedeHoteleira\x12N\n\tBookHotel\x12\x1f.redeHoteleira.BookHotelRequest\x1a .redeHoteleira.BookHotelResponse\x12`\n\x0f\x43\x61ncelBookHotel\x12%.redeHoteleira.CancelBookHotelRequest\x1a&.redeHoteleira.CancelBookHotelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'redeHoteleira_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKHOTELREQUEST']._serialized_start=38
  _globals['_BOOKHOTELREQUEST']._serialized_end=114
  _globals['_BOOKHOTELRESPONSE']._serialized_start=116
  _globals['_BOOKHOTELRESPONSE']._serialized_end=192
  _globals['_CANCELBOOKHOTELREQUEST']._serialized_start=194
  _globals['_CANCELBOOKHOTELREQUEST']._serialized_end=230
  _globals['_CANCELBOOKHOTELRESPONSE']._serialized_start=232
  _globals['_CANCELBOOKHOTELRESPONSE']._serialized_end=290
  _globals['_REDEHOTELEIRA']._serialized_start=293
  _globals['_REDEHOTELEIRA']._serialized_end=486
# @@protoc_insertion_point(module_scope)
