# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import companhiaAerea_pb2 as companhiaAerea__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in companhiaAerea_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompanhiaAereaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookFly = channel.unary_unary(
                '/companhiaAerea.CompanhiaAerea/BookFly',
                request_serializer=companhiaAerea__pb2.BookFlyRequest.SerializeToString,
                response_deserializer=companhiaAerea__pb2.BookFlyResponse.FromString,
                _registered_method=True)
        self.CancelBookFly = channel.unary_unary(
                '/companhiaAerea.CompanhiaAerea/CancelBookFly',
                request_serializer=companhiaAerea__pb2.CancelBookFlyRequest.SerializeToString,
                response_deserializer=companhiaAerea__pb2.CancelBookFlyResponse.FromString,
                _registered_method=True)


class CompanhiaAereaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookFly(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBookFly(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanhiaAereaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookFly': grpc.unary_unary_rpc_method_handler(
                    servicer.BookFly,
                    request_deserializer=companhiaAerea__pb2.BookFlyRequest.FromString,
                    response_serializer=companhiaAerea__pb2.BookFlyResponse.SerializeToString,
            ),
            'CancelBookFly': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBookFly,
                    request_deserializer=companhiaAerea__pb2.CancelBookFlyRequest.FromString,
                    response_serializer=companhiaAerea__pb2.CancelBookFlyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companhiaAerea.CompanhiaAerea', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('companhiaAerea.CompanhiaAerea', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanhiaAerea(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookFly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companhiaAerea.CompanhiaAerea/BookFly',
            companhiaAerea__pb2.BookFlyRequest.SerializeToString,
            companhiaAerea__pb2.BookFlyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBookFly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companhiaAerea.CompanhiaAerea/CancelBookFly',
            companhiaAerea__pb2.CancelBookFlyRequest.SerializeToString,
            companhiaAerea__pb2.CancelBookFlyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
