# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import locadoraCarro_pb2 as locadoraCarro__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in locadoraCarro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocadoraCarroStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookCar = channel.unary_unary(
                '/locadoraCarro.LocadoraCarro/BookCar',
                request_serializer=locadoraCarro__pb2.BookCarRequest.SerializeToString,
                response_deserializer=locadoraCarro__pb2.BookCarResponse.FromString,
                _registered_method=True)
        self.CancelBookCar = channel.unary_unary(
                '/locadoraCarro.LocadoraCarro/CancelBookCar',
                request_serializer=locadoraCarro__pb2.CancelBookCarRequest.SerializeToString,
                response_deserializer=locadoraCarro__pb2.CancelBookCarResponse.FromString,
                _registered_method=True)


class LocadoraCarroServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBookCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocadoraCarroServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookCar': grpc.unary_unary_rpc_method_handler(
                    servicer.BookCar,
                    request_deserializer=locadoraCarro__pb2.BookCarRequest.FromString,
                    response_serializer=locadoraCarro__pb2.BookCarResponse.SerializeToString,
            ),
            'CancelBookCar': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBookCar,
                    request_deserializer=locadoraCarro__pb2.CancelBookCarRequest.FromString,
                    response_serializer=locadoraCarro__pb2.CancelBookCarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'locadoraCarro.LocadoraCarro', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('locadoraCarro.LocadoraCarro', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocadoraCarro(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/locadoraCarro.LocadoraCarro/BookCar',
            locadoraCarro__pb2.BookCarRequest.SerializeToString,
            locadoraCarro__pb2.BookCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBookCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/locadoraCarro.LocadoraCarro/CancelBookCar',
            locadoraCarro__pb2.CancelBookCarRequest.SerializeToString,
            locadoraCarro__pb2.CancelBookCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
